### PR TITLE
Rename the tests folder to be consistent with the name of the assembly

### PR DESCRIPTION
**Pull request by explorer14**
This PR simply makes the names of the integration tests folder consistent with that of the tests assembly itself.

### CODE REVIEW

**Comment by explorer14** [comment]
@craigwardman 1+ year was enough time to review a PR I would've thought! 😂

**Comment by explorer14** [comment]
btw, your code has also been preserved for the future generations to enjoy:

image

**Comment by explorer14** [comment]
https://github.blog/2020-07-16-github-archive-program-the-journey-of-the-worlds-open-source-code-to-the-arctic/

**Comment by craigwardman** [comment]
That's great, chunking penguin client.

**Pull request merged**
